_name: null
beam: 5
constraints: null
decoding_format: null
diverse_beam_groups: -1
diverse_beam_strength: 0.5
diversity_rate: -1.0
iter_decode_eos_penalty: 0.0
iter_decode_force_max_iter: false
iter_decode_max_iter: 10
iter_decode_with_beam: 1
iter_decode_with_external_reranker: false
lenpen: 1.0
lm_path: null
lm_weight: 0.0
match_source_len: false
max_len_a: 0.0
max_len_b: 200
min_len: 1
nbest: 1
no_beamable_mm: false
no_early_stop: false
no_repeat_ngram_size: 0
no_seed_provided: false
prefix_size: 0
print_alignment: null
print_step: false
replace_unk: null
retain_dropout: false
retain_dropout_modules: null
retain_iter_history: false
sacrebleu: true
sampling: false
sampling_topk: -1
sampling_topp: -1.0
score_reference: false
temperature: 1.0
unkpen: 0.0
unnormalized: false
